version: "3.9"

networks:
  docker1: { external: true }
  docker2: { external: true }


services:

# ---------- prod

  button-relay: &baseline
    extends: { file: ../docker-compose-common.yaml, service: x-prod }

    container_name: button-relay
    hostname: button-relay

    devices:
      - /dev/tty-button-relay:/dev/ttyUSB0

      # Need to run with the host's user id's, because need access to the real
      # dialout group.  Note that host uid 901 must also be added to gid/dialout.
    userns_mode: host

    volumes:
      - /rw/dv/button-relay/var_log:/var/log

    ports:
      - 8084:8080

    image: ktools/button-relay:live

