
##autostart: 5

ports:
  - 8084:8080

# Need to run with the host's user id's, because need access to the real
# dialout group.  Note that host uid 901 must also be added to gid/dialout.
extra_docker: "--userns=host"

mount_devices:
  - /dev/ttyACM*
  - /dev/ttyUSB*

mount_rw:
  - var_log: /var/log

vols:
  - var_log:
    owner: user/buttonrelay
