
include ../../common/Makefile-docker

# ---------- pass-throughs

all: docker-all
comp:  # n/a
clean: docker-clean
install: docker-install
test: docker-test
uninstall: docker-uninstall
update: docker-update
