#!/usr/bin/python3

# TODO!: fails on blue: /bin/cp: cannot stat '/rw/dv/squiddock/var_log_squid': No such file or directory


import argparse, base64, os, subprocess, ssl, sys, time

sys.path.append('/root/bin')
import kcore.docker_lib as D


def main():
    ap = argparse.ArgumentParser(description='squiddock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = D.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    if args.run: time.sleep(2)  #  Give squid a chance to start up.

    D.web_expect('little place', 'www.kenstillson.com', '/', proxy_host=ip+':3128')

    prefix = dv + ('/' if args.prod else '/_rw_dv_squiddock_')
    D.file_expect('http://www.kenstillson.com/', prefix + 'var_log_squid/access.log')

    print('pass')
    

if __name__ == "__main__":
  main()

