# This config uses TLS, and requires authN for all operations (read & write).

# It would be nice to not require for GET/HEAD, but the "v2" protocol of the
# registry isn't compatible with this (it logs in using only indistinguishable
# GET operations, and when it doesn't get challenged, it stops sending auth
# headers completely).

# If your cert is not issued by a default-trusted CA, then the cert needs to
# be configured as trusted.  See ./README-cert.md

name: registry_rw

ports:
  - 5444:5444

log: j

env:
  - REGISTRY_HTTP_ADDR=0.0.0.0:5444
  - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/regdock.crt
  - REGISTRY_HTTP_TLS_KEY=/etc/regdock.key
  - REGISTRY_AUTH=htpasswd
  - REGISTRY_AUTH_HTPASSWD_REALM="Registry"
  - REGISTRY_AUTH_HTPASSWD_PATH=/etc//htpasswd

mount_persistent_test_ro:
  - var_lib_reg: /var/lib/registry
