
ports:
  - 80:8080
  - 443:8443
  - 8443:8443

mount_ro:
  - etc_apache2_keys: /etc/apache2/keys
  - var_www: /var/www
  - /rw/dv/nagdock/var_nagios: /var/nagios

mount_logs:
  - var_log_apache2: /var/log/apache2

mount_persistent:
  - /rw/dv/nagdock/var_nagios/rw: /var/nagios/rw
