
# TODO!: need to provide code to generate host-keys and put them in place, and
# to put git-ro-test-key.pub as a testing-only acceptable pubkey

# ---------- pass-throughs

include ../../common/Makefile-docker

all: docker-all
comp:  # n/a
clean: docker-clean
install: docker-install
test: docker-test
uninstall: docker-uninstall
update: docker-update
