#!/usr/bin/python3

import argparse, atexit, os, shutil, sys, subprocess, tempfile, time

sys.path.append('/root/bin')
import kcore.docker_lib as D


def cleanup(tmpdir, orig_dir):
    os.chdir(orig_dir)
    shutil.rmtree(tmpdir)


def main():
    ap = argparse.ArgumentParser(description='gitdock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = D.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    orig_dir = os.getcwd()
    tmpdir = tempfile.mkdtemp()
    D.emit('tmpdir: ' + tmpdir)
    atexit.register(cleanup, tmpdir, orig_dir)
    os.chdir(tmpdir)

    subprocess.check_call(
        ['git', 'clone', 'git-ro@%s:git/rc.git' % ip],
        env={ 'GIT_SSH_COMMAND': '/usr/bin/ssh -i /root/docker-dev/gitdock/git-ro-test-key -o StrictHostKeyChecking=no' })
    D.file_expect('exit with status', 'rc/.profile')

    print('pass')
    

if __name__ == "__main__":
  main()

