'''Example procmon whitelist

This is an example based on the original author's actual whitelist (with a few
strategic entries removed).  To make your own, copy this as a starting point to
private.d/procmon_whitelist.py, and modify as needed for your system.
'''

from procmon_wl_type import WL

#      Container    user           child? rqrd?  regex
WHITELIST = [
    WL('*',         'root',        False, False, r'runc --root /var/run/docker/runtime-runc/moby --log'),
    WL('*',         'root',        False, False, r'runc init'),
    WL('/',         '*',           False, False, r'/lib/systemd/systemd --(system|user)'),
    WL('/',         '*',           False, False, r'\(sd-pam\)'),
    WL('/',         'blue-backup', False, False, r'rsync '),
    WL('/',         'blue-backup', False, False, r'sshd: blue-backup'),
    WL('/',         'ken',         False, False, r'(/bin/sh -c *)?/usr/local/bin/hc tree'),
    WL('/',         'ken',         False, False, r'/usr/sbin/sendmail'),
    WL('/',         'man',         False, False, r'/usr/bin/mandb --quiet'),
    WL('/',         'messagebus',  False, True,  r'/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation'),
    WL('/',         'nobody',      False, False, r'(/bin/bash -c *)?/bin/ping -c1 -q -w4 hs-front'),
    WL('/',         'nobody',      False, False, r'/bin/sleep'),
    WL('/',         'nobody',      False, False, r'/usr/bin/python3 /root/ktools/procmon/procmon'),
    WL('/',         'nobody',      False, True,  r'/usr/local/bin/dhcp-helper -e eth1 -s 192.168.2.2'),
    WL('/',         'ntp',         False, False, r'/usr/sbin/ntpd -p /var/run/ntpd.pid'),
    WL('/',         'root',        False, False, r'(/bin/bash -c *)?.HC'),
    WL('/',         'root',        False, False, r'(/bin/bash -c *)?{ .SSR -o'),
    WL('/',         'root',        False, False, r'.*chmod 644 /var/run/dmap'),
    WL('/',         'root',        False, False, r'/bin/(ba)?sh -c test -x /usr/sbin/anacron'),
    WL('/',         'root',        False, False, r'/bin/(ba)?sh( -c)? */root/bin/d-run --cd rclonedock --fg --settings'),
    WL('/',         'root',        False, False, r'/bin/login'),
    WL('/',         'root',        False, False, r'/bin/systemd-tty-ask-password-agent'),
    WL('/',         'root',        False, False, r'/sbin/agetty '),
    WL('/',         'root',        False, False, r'/sbin/fstrim --fstab'),
    WL('/',         'root',        False, False, r'/sbin/init'),
    WL('/',         'root',        False, False, r'/usr/bin/containerd'),
    WL('/',         'root',        False, False, r'/usr/bin/docker run --name rclonedock'),
    WL('/',         'root',        False, False, r'/usr/bin/docker-proxy -proto'),
    WL('/',         'root',        False, False, r'/usr/bin/dockerd -H'),
    WL('/',         'root',        False, False, r'/usr/bin/python3 /root/bin/d-run --cd rclonedock --fg --settings'),
    WL('/',         'root',        False, False, r'/usr/bin/python3 /usr/local/bin/hc'),
    WL('/',         'root',        False, False, r'/usr/bin/python3 /usr/local/bin/sunsetter.py'),
    WL('/',         'root',        False, False, r'/usr/lib/openssh/sftp-server'),
    WL('/',         'root',        False, False, r'/usr/local/bin/hc'),
    WL('/',         'root',        False, False, r'/usr/sbin/CRON -f'),
    WL('/',         'root',        False, False, r'/usr/sbin/sendmail -i -FCronDaemon'),
    WL('/',         'root',        False, False, r'containerd-shim'),
    WL('/',         'root',        False, False, r'ddclient'),
    WL('/',         'root',        False, False, r'docker ps --format'),
    WL('/',         'root',        False, False, r'docker-containerd --config /var/run/docker/containerd/containerd.toml'),
    WL('/',         'root',        False, False, r'sleep'),
    WL('/',         'root',        False, False, r'sshd: root@notty'),
    WL('/',         'root',        False, True,  r'/lib/systemd/systemd-journald'),
    WL('/',         'root',        False, True,  r'/lib/systemd/systemd-logind'),
    WL('/',         'root',        False, True,  r'/lib/systemd/systemd-udevd'),
    WL('/',         'root',        False, True,  r'/sbin/dhclient'),
    WL('/',         'root',        False, True,  r'/usr/bin/python3? /usr/bin/fail2ban-server'),
    WL('/',         'root',        False, True,  r'/usr/lib/accountsservice/accounts-daemon'),
    WL('/',         'root',        False, True,  r'/usr/lib/policykit-1/polkitd --no-debug'),
    WL('/',         'root',        False, True,  r'/usr/sbin/acpid'),
    WL('/',         'root',        False, True,  r'/usr/sbin/atd -f'),
    WL('/',         'root',        False, True,  r'/usr/sbin/cron -f'),
    WL('/',         'root',        False, True,  r'/usr/sbin/irqbalance'),
    WL('/',         'root',        False, True,  r'/usr/sbin/rngd -r /dev/hwrng'),
    WL('/',         'root',        False, True,  r'/usr/sbin/rsyslogd -n'),
    WL('/',         'root',        False, True,  r'/usr/sbin/smartd -n'),
    WL('/',         'root',        False, True,  r'sshd: /usr/sbin/sshd -D'),
    WL('/',         'root',        True,  False, r'(/bin/sh -c *)?run-parts --report /etc/cron'),
    WL('/',         'root',        True,  False, r'/bin/(ba)?sh( -c)? */root/bin/d 01 nagdock'),
    WL('/',         'root',        True,  False, r'/bin/(ba)?sh( -c)? */usr/local/bin/update-ddns'),
    WL('/',         'root',        True,  False, r'/bin/sh -c */root/bin/rsnap-diff'),
    WL('/',         'root',        True,  False, r'/bin/sh -c */root/bin/run-rsnapshot'),
    WL('/',         'root',        True,  False, r'/usr/sbin/logrotate /etc/logrotate.conf'),
    WL('/',         'root',        True,  False, r'bash -c chown droot.dwatch /rw/dv/blender/work/'),
    WL('/',         'root',        True,  False, r'sshd: (blue-backup|rsnap)'),
    WL('/',         'uuidd',       False, False, r'/usr/sbin/uuidd'),
    WL('blender',   'droot',       False, False, r'/bin/bash /etc/init '),
    WL('blender',   'droot',       False, False, r'blender -b'),
    WL('dlnadock',  'dminidlna',   False, False, r'/usr/sbin/minidlnad'),
    WL('dlnadock',  'root',        False, False, r'/bin/bash /etc/init'),
    WL('dlnadock',  'root',        False, False, r'/usr/bin/encfs'),
    WL('dlnadock',  'root',        False, False, r'sleep'),
    WL('dnsdock',   'ddnsmasq',    False, True,  r'/usr/sbin/dnsmasq --conf-file=/etc/dnsmasq/dnsmasq.conf'),
    WL('eximdock',  'dexim',       False, True,  r'/usr/sbin/exim'),
    WL('filewatchdock', 'dwatch',  False, True,  r'/usr/bin/python3 /home/watch/filewatch'),
    WL('fsdock',    'dken',        False, False, r'/usr/lib/ssh/sftp-server'),
    WL('fsdock',    'dken',        False, False, r'sshd: ken@notty'),
    WL('fsdock',    'dpi2',        False, False, r'/usr/lib/ssh/sftp-server'),
    WL('fsdock',    'dpi2',        False, False, r'sshd: pi2@notty'),
    WL('fsdock',    'droot',       False, False, r'/usr/sbin/rsyslogd'),
    WL('fsdock',    'droot',       False, False, r'sshd: /usr/sbin/sshd -D'),
    WL('fsdock',    'droot',       False, False, r'sshd: ken \[priv\]'),
    WL('fsdock',    'droot',       False, False, r'sshd: pi2 \[priv\]'),
    WL('fsdock',    'dsshd',       False, False, r'sshd: ken'),
    WL('gitdock',   '*',           False, False, r'sshd: [a-z]* ?\[net\]'),
    WL('gitdock',   'droot',       False, False, r'sshd: [a-z0-9-]* \[priv\]'),
    WL('gitdock',   'droot',       False, False, r'sshd: \[accepted\]'),
    WL('gitdock',   'droot',       False, True,  r'(sshd: )?/usr/sbin/sshd -D -e'),
    WL('home-control', 'dhc',      False, False, r'/usr/bin/python3 /home/hc/home_control_service.py'),
    WL('homesecdock', 'dhs',       False, False, r'/usr/bin/python3 /home/hs/homesec.py'),
    WL('keymaster', 'dkm',         False, False, r'/usr/bin/python3 /home/km/km.py'),
    WL('lsyncdock', 'droot',       True,  True,  r'/usr/bin/lsyncd -nodaemon /etc/lsyncd/lsyncd.conf.lua'),
    WL('nagdock',   'dnagios',     True,  True,  r'/usr/sbin/nagios'),
    WL('nddock',    '201',         True,  False, r'/usr/sbin/netdata.*'),
    WL('nddock',    'root',        False, False, r'/bin/bash'),
    WL('prometheus','265534',      False, True,  r'/bin/prometheus --config.file=/etc/prometheus/prometheus.yml'),
    WL('rclonedock','droot',       False, False, r'/bin/bash /etc/init'),
    WL('rclonedock','droot',       False, False, r'/root/bin/rclone (sync|copy)'),
    WL('rclonedock','droot',       False, False, r'/usr/bin/encfs --extpass /usr/local/bin/kmc encfs-default /root/gdrive /root/gdrive-efs'),
    WL('rclonedock','droot',       False, False, r'/usr/bin/script --append --flush --return --command /etc/init'),
    WL('rclonedock','droot',       False, False, r'fgrep -v non'),
    WL('rclonedock','root',        False, False, r'/bin/bash /etc/init'),
    WL('rclonedock','root',        False, False, r'/root/bin/rclone (sync|copy)'),
    WL('rclonedock','root',        False, False, r'fgrep -v non'),
    WL('rsnapdock', 'root',        True,  False, r'/bin/bash /etc/init'),
    WL('rsnapdock', 'root',        True,  False, r'/usr/bin/perl -w /usr/bin/rsnapshot'),
    WL('sambadock', 'dken',        True,  False, r'/usr/sbin/smbd'),
    WL('squiddock', 'dsquid',      False, False, r'\(logfile-daemon'),
    WL('squiddock', 'dsquid',      False, False, r'\(squid-'),
    WL('squiddock', 'dsquid',      False, False, r'\(unlinkd'),
    WL('squiddock', 'dsquid',      False, True,  r'/usr/sbin/squid'),
    WL('sshdock',   '*',           False, False, r'sshd: [a-z0-9]* ?\[net\]'),
    WL('sshdock',   'dhomesec1',   False, False, r'rsync --server'),
    WL('sshdock',   'dhomesec1',   False, False, r'sshd: homesec1'),
    WL('sshdock',   'dhomesec2',   False, False, r'rsync --server'),
    WL('sshdock',   'dhomesec2',   False, False, r'sshd: homesec2'),
    WL('sshdock',   'dhs-front',   False, False, r'rsync --server'),
    WL('sshdock',   'dhs-front',   False, False, r'sshd: hs-front'),
    WL('sshdock',   'dken',        False, False, r'rsync'),
    WL('sshdock',   'droot',       False, False, r'sshd: [A-Za-z0-9-]* \[priv\]'),
    WL('sshdock',   'droot',       False, False, r'sshd: \[accepted\]'),
    WL('sshdock',   'droot',       False, True,  r'(sshd: )?/usr/sbin/sshd -D'),
    WL('sshdock',   'droot',       False, True,  r'/usr/sbin/rsyslogd'),
    WL('sshdock',   'dsshd',       True,  False, r'sshd: '),
    WL('sshdock',   'dtunnel-glowbox1',   False, False, r'sshd: tunnel-glowbox1'),
    WL('syslogdock', 'dsyslog',    False, False, r'/usr/sbin/ssmtp'),
    WL('syslogdock', 'dsyslog',    False, True,  r'/bin/bash /usr/local/sbin/log-mailer'),
    WL('syslogdock', 'dsyslog',    False, True,  r'/usr/bin/python. /usr/bin/supervisord -n -c /etc/supervisord.conf'),
    WL('syslogdock', 'dsyslog',    False, True,  r'/usr/sbin/syslog-ng'),
    WL('webdock',   'dapache',     False, False, r'(/usr/bin/python3 )?/usr/lib/cgi-bin/kcmd.cgi'),
    WL('webdock',   'dapache',     False, False, r'(/usr/bin/python3 )?/usr/local/bin/party-lights'),
    WL('webdock',   'dapache',     False, False, r'/bin/bash /usr/lib/cgi-bin/nagios-healthz.cgi'),
    WL('webdock',   'dapache',     False, False, r'/usr/lib/nagios/cgi-bin/status.cgi'),
    WL('webdock',   'dapache',     False, True,  r'/usr/sbin/httpd'),
]

#      Container    user           child? rqrd?  regex
GREYLIST = [
    WL('/',         'ken',         False, False,  'sshd: ken'),
    WL('/',         'root',        False, False,  '/usr/bin/python3 /usr/bin/glances'),
    WL('/',         'root',        False, False,  '/usr/bin/ssh-agent'),
    WL('/',         'root',        False, False,  'sshd: ken'),
    WL('/',         'root',        False, False,  'sshd: root \[priv\]'),
    WL('/',         'root',        True,  False,  'SCREEN -D -R'),
    WL('/',         'root',        True,  False,  'sshd: root@pts/.'),
    WL('git',       'root',        False, False,  'sshd: ken'),
]

# You can add custom/additional handlers here.  (Placed here because this file
# is generally overriden by private.d/procmon_whitelist.py, so this enables
# private handlers).

ADDL_HANDLERS = {
    '/example': lambda request: 'hithere!'
}
