
autostart: 5

# Port mapping must be done via iptables DNAT rather than docker proxy,
# to preserve incoming peer IP addresses for client access control check.

# Routing to keymanager works better going direct to docker IP
extra_docker: "--add-host=keys:192.168.2.33"

mount_rw:
  - hs_data: /home/hs/data
  - var_log_hs: /var/log/homesec

test_env: "TEST=1"
test_ports: ['1111:1111']

