
autostart: 5

# Port mapping must be done via iptables DNAT rather than docker proxy,
# to preserve incoming peer IP addresses for client access control check.

mount_persistent_test_copy_files:
  - hs_data: /home/hs/data

mount_logs:
  - var_log_hs: /var/log/homesec

# Routing to keymanager works better going direct to docker IP
extra_docker: "--add-host=keys:192.168.2.33"

# -----

test_env: "TEST=1"
test_ports: ['1111:1111']
