#!/usr/bin/python3

'''This test can't send an email without credentials; see Test-prod for that.
Instead, we *try* to send an email and expect it to go nowhere, and check that
the errors look like what we expect, rather than looking like configuration
errors, or failure to start the exim server, etc. '''

# TODO: complete impl

import sys
sys.exit(0)
