#!/usr/bin/python

import argparse, base64, os, subprocess, ssl, sys, time

sys.path.append('/root/bin')
import d_lib


def main():
    ap = argparse.ArgumentParser(description='squiddock test')
    d_lib.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = d_lib.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    if args.run: time.sleep(2)  #  Give squid a chance to start up.

    d_lib.web_expect('little place', 'www.kenstillson.com', '/', proxy_host=ip+':3128')

    prefix = dv + ('/' if args.prod else '/_rw_dv_squiddock_')
    d_lib.file_expect('http://www.kenstillson.com/', prefix + 'var_log_squid/access.log')

    print('pass')
    

if __name__ == "__main__":
  main()

