#!/bin/bash

if [[ "$1" == "" ]]; then
  echo "Provide rsnapshot param (e.g. 'daily') to container launch."
  exit 2
fi

# The build happened with userns turned on.  Now that we're running without
# the ns mapping, we need to put some files back to their real-uid owners.
/bin/chown -R root.root /root/.ssh

# TEST MODE
if [[ "$1" == "test" ]]; then
  echo "test mode"
  /usr/bin/rsnapshot -v -c /etc/rsnapshot-test.conf daily
  status=$?
  echo "test run done; delaying 10 seconds for test to catch results."
  sleep 10
  exit $status
fi

# MAIN
exec /usr/bin/rsnapshot "$@"

