#!/bin/bash

EXPECT="$1"
shift
CURL_PARAMS="$@"

outfile="/tmp/x"
cmd="curl -s -o $outfile ${CURL_PARAMS}"
$cmd

fgrep -q "$EXPECT" $outfile && { echo "OK"; exit 0; }

echo "CRITICAL- NOT FOUND: $EXPECT"
if [[ "$VERBOSE" != "" ]]; then
  echo "CMD: $cmd"
  echo "GOT: $(cat $outfile)"
fi
exit 2
