#!/bin/bash

SVC="${SVC:-/home/km/km.py}"

if [[ -v TEST ]]; then
    echo ""
    echo "!! TEST MODE !!  (log to stderr and no syslog)"
    echo ""
    COMMAND="$SVC --debug --datafile km-test.data.pcrypt --db-filename kcore_auth_db-test.data.pcrypt --logfile -"

elif [[ -v DEBUG ]]; then
    COMMAND="$SVC --debug --logfile -"

else
    FLAGS="${FLAGS:- --logfile /var/log/km/km.log --syslog}"
    COMMAND="$SVC $FLAGS"
fi

echo "init transferring to: $COMMAND"
exec $COMMAND
