#!/bin/bash
# Output a report of the files that have changed recently in our rsnapshot backup.

BASE=/mnt/rsnap
EXC=/root/bin/rsnap-diff.exclude

# If $1 is defined, use that as our output file; else use a random temp file.
out=${1:-$(/bin/tempfile)}
# If $2 is defined, use that as our OLD directory
OLD=${2:-daily.1}
# If $3 is defined, use that as our NEW directory
NEW=${3:-daily.0}

cd ${BASE}
{ /usr/bin/diff -rq ${NEW} ${OLD} | \
  /bin/sed -e 's@: @/@' | \
  /bin/egrep -v -f ${EXC} > ${out}; \
} 2>&1 | fgrep -v "No such file" | \
         fgrep -v "Too many levels" | \
         fgrep -v "recursive directory loop"

echo ""
echo "rsnapshot diff report ${NEW} vs ${OLD}"

echo ""
echo "Changes (see ~/bin/D)"
/bin/grep differ ${out} | /usr/bin/cut -d" " -f2 | /bin/sed -e "s:${NEW}/::"

echo ""
echo "Deletions"
/bin/grep Only ${out} | /bin/grep ${OLD} | /usr/bin/cut -d" " -f3,4

echo ""
echo "Additions"
/bin/grep Only ${out} | /bin/grep ${NEW} | /usr/bin/cut -d" " -f3,4

if [[ "$1" == "" ]]; then
  /bin/rm -f ${out}
fi
