#!/bin/bash
# Output a report of the files that have changed recently in our rsnapshot backup.

# ----- input params & defaults

# If $1 is defined, use that as our output file; else use a random temp file.

##@@ OUT=${1:-$(/bin/tempfile)}
OUT=/root/tmp/rsnap-diff.tmp

# If $2 is defined, use that as our OLD directory (relative to $BASE, below)
OLD=${2:-daily.1}
# If $3 is defined, use that as our NEW directory (relative to $BASE, below)
NEW=${3:-daily.0}

# ----- control constants

MYDIR=$(realpath $(dirname $0))
BASE=${BASE:-/mnt/rsnap}
EXC=${EXC:-${MYDIR}/rsnap-diff.exclude}
CONSOLIDATE_FILE=${CONSOLIDATE_FILE:-${MYDIR}/rsnap-diff.consol}
CONSOLIDATE=${CONSOLIDATE:-/root/bin/substring_counter -r -s file:${CONSOLIDATE_FILE}}

# ----- compute the diff

if [[ "$REUSE_OUT" != "1" ]]; then
  cd ${BASE}
  { /usr/bin/diff -rq ${NEW} ${OLD} | \
    /bin/sed -e 's@: @/@' | \
    /bin/egrep -v -f ${EXC} > ${OUT}; \
  } 2>&1 | fgrep -v "No such file" | \
           fgrep -v "Too many levels" | \
           fgrep -v "recursive directory loop"
fi

# ----- output phase: separate into changes, deletions and additions

echo ""
echo "rsnapshot diff report ${NEW} vs ${OLD}"

echo ""
echo "Changes (see ~/bin/D)"
/bin/grep differ ${OUT} | /usr/bin/cut -d" " -f2 | /bin/sed -e "s:${NEW}/::" | ${CONSOLIDATE}

echo ""
echo "Deletions"
/bin/grep Only ${OUT} | /bin/grep ${OLD} | /usr/bin/cut -d" " -f3,4 | ${CONSOLIDATE}

echo ""
echo "Additions"
/bin/grep Only ${OUT} | /bin/grep ${NEW} | /usr/bin/cut -d" " -f3,4 | ${CONSOLIDATE}

# ----- cleanup

if [[ "$1" == "" ]]; then
  /bin/rm -f ${OUT}
fi
