#!/usr/bin/python3

# TODO!: test fails on blue with something about hostkey validation...  investigate

import argparse, os, subprocess, sys, time

sys.path.append('/root/bin')
import kcore.docker_lib as D


def main():
    ap = argparse.ArgumentParser(description='rsnapdock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = D.launch_or_find_container(args, ['--extra-init=test'])
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    test_file = '/rw/dv/TMP/rsnapdock/_rw_mnt_rsnap/daily.0/jack/etc/shadow'
    D.emit('starting wait for ' + test_file)

    for i in range(100):
        time.sleep(3)
        size = os.path.getsize(test_file) if os.path.exists(test_file) else -1
        if size > 0: break
        if i % 3 == 0: D.emit('watching for shadow %d/100  [%d]' % (i, size))

    D.file_expect('root:!:', test_file)

    print('pass')
    

if __name__ == "__main__":
  main()

