#!/usr/bin/python

import argparse, os, subprocess, sys, time

sys.path.append('/root/bin')
import d_lib


def main():
    ap = argparse.ArgumentParser(description='rsnapdock test')
    d_lib.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = d_lib.launch_or_find_container(args, ['--extra-init=test'])
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    test_file = '/rw/dv/TMP/rsnapdock/_rw_mnt_rsnap/daily.0/jack/etc/shadow'
    d_lib.emit('starting wait for ' + test_file)

    for i in range(100):
        time.sleep(3)
        size = os.path.getsize(test_file) if os.path.exists(test_file) else -1
        if size > 0: break
        if i % 3 == 0: d_lib.emit('watching for shadow %d/100  [%d]' % (i, size))

    d_lib.file_expect('root:!:', test_file)

    print('pass')
    

if __name__ == "__main__":
  main()

