
# Port mapping must be done via iptables NAT rather than docker proxy, because
# we need to the preserve incoming IP address-- it's part of the access control
# checks.

autostart: 2

mount_logs:
  - var_log_km: /var/log/km

# -----

test_env: "TEST=1"
test_ports: ['4444:4444']

# ----

mount_rw:
  - var_log_km: /var/log/km
