

all:
	@echo nothing to be done for :all

clean:
	@echo nothing to be done for :clean

install:
	@echo nothing to be done for :install

test:
	@echo nothing to be done for :test

update:
	@echo nothing to be done for :update

uninstall:
	@echo nothing to be done for :uninstall
