
# Port mapping must be done via iptables NAT rather than docker proxy, because
# we need to the preserve incoming IP address-- it's part of the access control
# checks.

mount_logs:
  - var_log_km: /var/log/km

