#!/usr/bin/python

import argparse, os, subprocess, sys, time

sys.path.append('/root/bin')
import d_lib


def main():
    ap = argparse.ArgumentParser(description='kmdock test')
    d_lib.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = d_lib.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    if args.prod:
        sys.exit('cannot do in-place prod testing; test is destructive to its container.')

    d_lib.run_command_in_container(name, ['/bin/cp', '-f', '-a', '/home/km/km-test.data.gpg', '/home/km/km.data.gpg'])

    d_lib.web_expect('not ready', ip, '/test', port=4443, https=True)

    d_lib.web_expect('ok', ip, '/', post_params={'password': 'ken123'}, port=4443, https=True)

    d_lib.web_expect('hithere', ip, '/test', port=4443, https=True)

    d_lib.web_expect('ok', ip, '/healthz', port=4443, https=True)

    d_lib.web_expect('cleared', ip, '/qqq', port=4443, https=True)

    d_lib.web_expect('not ready', ip, '/test', port=4443, https=True)

    print('pass')
    

if __name__ == "__main__":
  main()

