#!/usr/bin/python

import json, os, smtplib, sys, urllib, urllib2
from email.mime.text import MIMEText


def get_param():
  data = os.environ.get('PATH_INFO', '').replace('/', '')
  if not data: data = urllib.unquote(os.environ.get('QUERY_STRING', ''))
  return data


def get_addr(latlong):
  try:
    str = urllib2.urlopen('http://maps.google.com/maps/api/geocode/json?latlng=%s&sensor=false' % latlong).read()
  except Exception as e:
    return 'lookup error %s' %e
  try:
    j = json.loads(str)
  except Exception as e:
    return 'json error %s' % e
  try:
    return j['results'][0]['formatted_address']
  except Exception as e:
    return 'decode error %s' % e

def sendmail(q, a):
  from_addr = '"jack reverse map" <kstillson@gmail.com>'
  to_addr = 'ken@point0.net'
  msg = MIMEText("Query: %s\nAddress: %s" % (q, a))
  msg['From'] = from_addr
  msg['To'] = to_addr
  msg['Subject'] = 'reverse map utilization'
  smtp = smtplib.SMTP('exim4')
  smtp.sendmail(from_addr, [to_addr], msg.as_string())
  smtp.quit()

def main():
  print "Content-Type: text/html\n\n"
  data = get_param()
  if not data:
    print "no data provided."
    sys.exit(0)
  q = 'https://maps.google.com/?q=LOCATION@%s&output=embed' % data
  a = get_addr(data)
  print '<html><body>'
  print '<p>lat / long: %s</p>' % data
  print '<p><h2>address: %s</h2></p>' % a
  print '<p><a href="%s" target="_new">Show Google map</a></p>' % q
  print '<iframe width="100%%" height="100%%" src="%s" id="mapframe"></iframe>' % q
  print '</body></html>'
  sendmail(q, a)


main()
