# This config uses TLS, but requires no authN, and the registry is mounted
# read-only.  This is a decent secure-default for standard operations.

# If your cert is not issued by a default-trusted CA, then the cert needs to
# be configured as trusted.  See ./README-cert.md

name: registry

ports:
  - 5443:443

log: j

env:
  - REGISTRY_HTTP_ADDR=0.0.0.0:443
  - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/regdock.crt
  - REGISTRY_HTTP_TLS_KEY=/etc/regdock.key

mount_ro:
  - var_lib_reg: /var/lib/registry
