# Configuration file for dnsmasq.


# Subnet plan
# special- 192.168.1.0:    static, fully trusted local infrastructure
# docker1- 192.168.2.0:    static, containers, detailed firewall rules
# docker2- 192.168.3.0:    static, containers, build/play area- no outbound limitations
# docker3- 192.168.4.0:    not in use
# green-   192.168.5.0:    dhcp fixed, no outbound limitations
# yellow-  192.168.6.0:    dhcp dyn,   wan only; no local       (guests, some untrusted h/w)
# blue-    192.168.7.0:    dhcp fixed, lan only; no internet    (some untrusted h/w)
# purple-  192.168.8.0:    dhcp fixed, outbound only via proxy  (pi's, etc)
# red-     192.168.9.0:    dhcp dyn,   no connectivity, alert on traffic

##interface=eth0

# Include a another lot of configuration options.
#conf-file=/etc/dnsmasq.more.conf
#conf-dir=/etc/dnsmasq.d

# ------------------------------------------------------------
# DNS

log-facility=/var/log/dnsmasq/dnsmasq.log

# FOR DEBUGGING:
##@@
log-queries

# Never forward plain names (without a dot or domain part)
domain-needed
# Never forward addresses in the non-routed address spaces.
bogus-priv

no-resolv
no-hosts
no-poll
stop-dns-rebind
#resolv-file=
addn-hosts=/etc/dnsmasq/dnsmasq.hosts

# Other name servers, with domain specs if they are for non-public domains.
server=8.8.8.8

# Add local-only domains here, queries in these domains are answered
# from /etc/hosts or DHCP only.
##@@ auth-server=h.point0.net,eth0
##@@ local=/h.point0.net/
##@@ local=//

# Set the domain for dnsmasq. this is optional, but if it is set, it
# does the following things.
# 1) Allows DHCP hosts to have fully qualified domain names, as long
#     as the domain part matches this setting.
# 2) Sets the "domain" DHCP option thereby potentially setting the
#    domain of all systems configured by DHCP
# 3) Provides the domain part for "expand-hosts"
domain=h.point0.net
expand-hosts

# ------------------------------------------------------------
# DHCP

log-dhcp
dhcp-leasefile=/var/log/dnsmasq/dnsmasq.leases

dhcp-authoritative
#auth-zone=h.point0.net

dhcp-hostsfile=/etc/dnsmasq/dnsmasq.macs

dhcp-range= tag:green,           192.168.5.1, static,         255.255.0.0, 192.168.255.255, 5h
dhcp-range= tag:yellow,          192.168.6.1, 192.168.6.200,  255.255.0.0, 192.168.255.255, 5h
dhcp-range= tag:blue,            192.168.7.1, static,         255.255.0.0, 192.168.255.255, 5h
dhcp-range= tag:purple,          192.168.8.1, static,         255.255.0.0, 192.168.255.255, 5h
dhcp-range= tag:!green, tag:!yellow, tag:!blue, tag:!purple, set:red, 192.168.9.1, 192.168.9.127,  255.255.0.0, 192.168.255.255, 10m

# Options for all net tags
dhcp-option=option:router,192.168.1.2

# -- tag-specific options

# internal connectivity allowed
dhcp-option=tag:green,  option:dns-server,192.168.1.2
dhcp-option=tag:green,  option:domain-search,h.point0.net
dhcp-option=tag:green,  option:ntp-server,192.168.1.2

dhcp-option=tag:blue,   option:dns-server,192.168.1.2
dhcp-option=tag:blue,   option:domain-search,h.point0.net
dhcp-option=tag:blue,   option:ntp-server,192.168.1.2

dhcp-option=tag:purple, option:dns-server,192.168.1.2
dhcp-option=tag:purple, option:domain-search,h.point0.net
dhcp-option=tag:purple, option:ntp-server,192.168.1.2

# internal connectivity NOT allowed
dhcp-option=tag:yellow, option:dns-server,8.8.8.8
dhcp-option=tag:red,    option:dns-server,8.8.8.8
