
# ---------- pass-throughs

include ../../etc/Makefile-docker

all: docker-all
comp:  # n/a
clean: docker-clean
install: docker-install
uninstall: docker-uninstall
update: docker-update


# ---------- local overrides

# No tests yet, nothing to do.
test:

