#!/usr/bin/python3

import argparse, os, re, sys, time

import kcore.docker_lib as D
import kcore.webserver as W

CMD_FILE = '/rw/dv/TMP/nagdock/_rw_dv_nagdock_var_nagios/rw/nagios.cmd'
LOG_FILE = '/rw/dv/TMP/nagdock/_rw_dv_nagdock_var_log_nagios/nagios.log'
STATUS_FILE = '/rw/dv/TMP/nagdock/_rw_dv_nagdock_var_nagios/status.dat'

PORT = 12345
UPDATE_DELAY = 5
MAX_UPDATE_DELAY = 20

HITS = 0
def default_handler(request):
  global HITS
  HITS += 1
  return 'all ok'


def send_cmd(cmd, alt=True):
  now = str(int(time.time()))
  msg = '[%s] %s\n' % (now, cmd.replace('$NOW', now))
  D.emit(f'sending: {msg.strip()}')
  with open(CMD_FILE, 'a') as f: f.write(msg)
  time.sleep(1)


def parse_nagios(nagfile):
  conf = []
  with open(nagfile) as f: source = f.read()
  for line in source.splitlines():
      line = line.strip()
      matchID = re.match(r"(?:\s*define)?\s*(\w+)\s+{", line)
      matchAttr = re.match(r"\s*(\w+)(?:=|\s+)(.*)", line)
      matchEndID = re.match(r"\s*}", line)
      if len(line) == 0 or line[0] == '#':
          pass
      elif matchID:
          identifier = matchID.group(1)
          cur = [identifier, {}]
      elif matchAttr:
          attribute = matchAttr.group(1)
          value = matchAttr.group(2).strip()
          cur[1][attribute] = value
      elif matchEndID and cur:
          conf.append(cur)
          del cur
  return conf


def find_test(conf):
  for i in conf:
    if i[1].get('service_description') == 'test-service':
      return i


def status_expect(field, expected_status, conf=None):
  if not conf: conf = parse_nagios(STATUS_FILE)
  status = find_test(conf)
  if not status: D.abort('unable to find test-service data')
  val = status[1].get(field)
  if val == expected_status:
      D.emit('success; field %s == %s' % (field, expected_status))
  else:
      D.abort('Field "%s" has wrong value %s != %s' % (field, val, expected_status))


def main():
    ap = argparse.ArgumentParser(description='nagdock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    if args.prod: sys.exit('sorry, in-place prod testing not supported')

    name, ip, cow, dv = D.launch_or_find_container(args, ['--extra-docker', '--env TEST=1'])
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    # Check incoming assumptions
    time.sleep(3)
    conf = parse_nagios(STATUS_FILE)
    status_expect('active_checks_enabled', '0', conf)
    status_expect('has_been_checked', '0', conf)

    # Enable checking
    send_cmd('ENABLE_SVC_CHECK;jack;test-service')
    send_cmd('SCHEDULE_FORCED_SVC_CHECK;jack;test-service;$NOW')
    D.emit('waiting for nagios to check (to up %s seconds)...' % MAX_UPDATE_DELAY)

    # test server is off, so expect failure.
    D.file_expect_within(MAX_UPDATE_DELAY, 'EXTERNAL COMMAND: ENABLE_SVC_CHECK;jack;test-service', LOG_FILE)
    D.file_expect('SERVICE ALERT: jack;test-service;CRITICAL;HARD;1;CRITICAL', LOG_FILE)
    time.sleep(UPDATE_DELAY)
    conf = parse_nagios(STATUS_FILE)
    status_expect('active_checks_enabled', '1', conf)
    status_expect('has_been_checked', '1', conf)
    status_expect('current_state', '2', conf)

    # now enable the test service and try again.
    ws = W.WebServer({None: default_handler}, use_standard_handlers=False)
    ws.start(port=PORT)

    send_cmd('SCHEDULE_FORCED_SVC_CHECK;jack;test-service;$NOW')
    D.emit('waiting for nagios to check (up to %s seconds)...' % MAX_UPDATE_DELAY)

    D.file_expect_within(MAX_UPDATE_DELAY, 'SERVICE ALERT: jack;test-service;OK;HARD;1;OK', LOG_FILE)
    if HITS == 0: D.abort(f'expected >=1 hit against test server, but saw {HITS}')

    '''TODO: At this point, we should be able to re-parse the status file
    and confirm the current state has changed to 0.  However, for reasons I
    don't understand, the status file doesn't seem to get updated unless we
    wait a really long time.  The checks about (against LOG_FILE and HITS)
    basically confirm that the daemon is working...  So I guess I'll leave
    this final bit of the test disabled for now.  Not happy about this..

    conf = parse_nagios(STATUS_FILE)
    status_expect('current_state', '0', conf)
    '''
    
    print('pass')
    

if __name__ == "__main__":
  main()
