
# need --privileged so can run container commands inside a container.
# --privileged requires no userns.
extra_docker: "-ti --userns=host --privileged --add-host=regdock:192.168.1.2"

# need full outbound connectivity; docker2 is intended for build env.
network: docker2

mount_persistent:
  - var_cache_apk: /var/cache/apk
  # Needed to avoid stacked overlays, also has side-effect of persisting image cache:
  - var_lib_containers: /var/lib/containers

mount_ro:
  # Bind in reference copy of the current source; primary use of
  # this is for the private.d directory, but can also be manually
  # copied into place for quicker iteration than extracting from
  # git on each /etc/init.
  - /root/dev/ktools: /root/ktools-ref
