#!/bin/bash

SVC="/home/hs/homesec.py"

if [[ -v TEST ]]; then
    echo "!! TEST MODE !!"
    COMMAND="$SVC --debug --logfile - --kauth-db-filename kcore_auth_db-test.data.gpg --kauth-db-password test123"

elif [[ -v DEBUG ]]; then
    echo "!! DEBUG MODE !!"
    COMMAND="$SVC --debug --logfile -"
    
else
    COMMAND="$SVC --logfile /var/log/hc/hc.log --syslog"
fi

echo "init transferring to: $COMMAND"
exec $COMMAND
