version: "3.9"

networks:
  docker1: { external: true }
  docker2: { external: true }


services:

# ---------- prod

  filewatchdock:
    extends: { file: ../docker-compose-common.yaml, service: x-prod }

    container_name: filewatchdock
    hostname: filewatchdock

    volumes:
      - /mnt/rsnap:/root/rsnap:ro
      - /rw/log:/root/syslog:ro
      - /rw/dv:/root/dv:ro
      - /rw/dv/dnsdock/var_log_dnsmasq:/root/dnsmasq:ro
      - /home/ken/share/rcam:/root/rcam:ro
      - /rw/dv/eximdock/var/spool/exim/input:/root/exim:ro

    ports:
      - 8082:8080
      - 8083:8080

    image: ktools/filewatchdock:live

    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - -T 3 http://127.0.0.1:8080/healthz | grep 'all ok' || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

# ---------- test

  test_filewatchdock:
    extends: { file: ../docker-compose-common.yaml, service: x-test }

    container_name: test_filewatchdock
    hostname: test_filewatchdock

    command: [ "pytest-3", "-p", "no:cacheprovider" ]

    image: ktools/filewatchdock:latest
