
autostart: 5

#ports:
#  - 8082:8080
#  - 8083:8080

mount_ro:
  - /home/ken/share:    /root/share
  - /mnt/rsnap:         /root/rsnap
  - /rw/dv/dnsdock/var_log_dnsmasq:        /root/dnsmasq
  - /rw/dv/eximdock/var/spool/exim/input:  /root/exim
  - /rw/dv:             /root/dv
  - /rw/log:            /root/syslog
  - /rw/var/local:      /root/var_local

test_mount_ro:
  - tmp2: /tmp

test_extra_init: test

