
# Everything else depends on DNS (d-run needs hostname lookups to get ip addresses), so start this very first.
autostart: 1

# Must manually assign IP; can't do DNS lookup when DNS isn't up yet.
ip: 192.168.2.2
test_ip: "-"

# caps required by dnsmasq
extra_docker:
  - "--cap-add=NET_ADMIN"
  - "--cap-add=NET_RAW"

ports:
  - '53:53'
  - '53:53/udp'   # was: - '192.168.1.2:53:53/udp'

## No point mapping port 67; broadcast doesn't make it through the bridge.
## Need to use dhcp_helper instead.
##  - '67:67'

mount_logs:
  - var_log_dnsmasq: /var/log/dnsmasq
