#!/usr/bin/python3

import argparse, socket, sys, time

sys.path.append('/root/bin')
import kcore.docker_lib as D


def main():
    ap = argparse.ArgumentParser(description='eximdock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = D.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    D.testing_container_expect(
        f'apk add bind-tools; nslookup jack {ip}; exit',
        'Address: 192.168.1.2')
    print('pass')
    

if __name__ == "__main__":
  main()

