#!/usr/bin/python

import argparse, subprocess, sys, time

sys.path.append('/root/bin')
import d_lib


def main():
    ap = argparse.ArgumentParser(description='kds-baseline test')
    d_lib.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = d_lib.launch_or_find_container(
        args, ['--cmd=/bin/sleep 5'])
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    d_lib.container_file_expect('APK_CLEANUP=1', name, '/prep')

    cookie = d_lib.gen_random_cookie()
    subprocess.check_call(['/usr/bin/docker', 'exec', '-u', '0', name,
      '/bin/bash', '-c', 'echo "%s" > /root/cookie' % cookie])
    d_lib.file_expect(cookie, cow + '/root/cookie')

    # d_lib.file_expect(cookie, cow + '/root/.bash_history')

    print('pass')
    

if __name__ == "__main__":
  main()

