
ports:
  - "2222:22"

debug_extra_init: "/usr/sbin/sshd -d"

mount_ro:
  - authkeys: /etc/ssh/authkeys
  - hostkeys: /etc/ssh/hostkeys
  - passwd: /etc/passwd

mount_persistent_test_ro:
  - home: /home

# Old rps config sends syslog to "sys"; redirect that to syslogdock.
extra_docker: "--add-host=sys:192.168.2.12"
