
# Need to disable user-ns mapping because it was also disabled in rsnapdock, so files in /mnt/rsnap are owned by their real-uid owners and we need access.
extra_docker: "--userns=host"

name: "rclonedock-servarica"
hostname: "rclonedock"

extra_init: "servarica"

mount_rw:
  - var_log: /var/log
  - /rw/mnt/rsnap/echo-back: /root/echo-back

mount_ro:
  - /rw/mnt/rsnap/daily.0: /root/src

