
extra_init: "test"

mount_logs:
  - var_log: /var/log

mount_persistent:
  - /rw/mnt/rsnap/echo-back: /root/echo-back

# need to use DNS assigned IP address to retrieve from keymaster, even in testing mode.
ip: "-"
