
# Need fuse for encfs
extra_docker:
  - "--cap-add=SYS_PTRACE"
  - "--device=/dev/fuse"
  - "--cap-add=SYS_ADMIN"
  - "--security-opt=apparmor:unconfined"

extra_init: "gdrive"

mount_rw:
  - var_log: /var/log
  - /home/ken/share/encfs/default: /root/gdrive

