
ip: 192.168.2.2

# Can't find syslog IP if we're not up yet.
log: json

extra_docker: "--cap-add=NET_ADMIN --cap-add=NET_RAW"

ports:
  - '53:53'
  - '192.168.1.2:53:53/udp'
## No point mapping port 67; broadcast doesn't make it through the bridge.
## Need to use dhcp_helper instead.
##  - '67:67'

mount_logs:
  - var_log_dnsmasq: /var/log/dnsmasq

