#!/usr/bin/python3

import argparse, socket, sys, time

sys.path.append('/root/bin')
import kcore.docker_lib as D


def main():
    ap = argparse.ArgumentParser(description='eximdock test')
    D.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = D.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    D.popen_expect(['/usr/bin/host', 'jack', ip], 'has address 192.168.1.2', '', 0)
    print('pass')
    

if __name__ == "__main__":
  main()

