#!/usr/bin/python

import argparse, socket, sys, time

sys.path.append('/root/bin')
import d_lib


def main():
    ap = argparse.ArgumentParser(description='eximdock test')
    d_lib.add_testing_args(ap)
    args = ap.parse_args()
    name, ip, cow, dv = d_lib.launch_or_find_container(args)
    if not cow or not ip: sys.exit('cannot find container %s' % name)

    d_lib.popen_expect(['/usr/bin/host', 'jack', ip], 'jack has address 192.168.1.2', '', 0)
    print('pass')
    

if __name__ == "__main__":
  main()

