
# TODO: move to a separate service...

# ---------- pass-throughs

include ../../common/Makefile-docker

all: docker-all
comp:  # n/a
clean: docker-clean
install: docker-install
test: docker-test
uninstall: docker-uninstall
update: docker-update
