#!/bin/bash

PROTO="http"
MAX_TIME="55"
RETRIES="10"
if [[ "$1" == "--quick" ]]; then
    MAX_TIME="3"
    RETRIES="0"
    shift
fi
if [[ "$1" == "--ssl" ]]; then PROTO="https"; shift; fi

SERVER="$1"
PORT="$2"
ADDR="${3:-/healthz}"

if [[ "${PORT}" == "" ]]; then
  if [[ "${PROTO}" == "https" ]]; then PORT=443; else PORT=80; fi
fi

URL="${PROTO}://${SERVER}:${PORT}${ADDR}"

ARGS="-L -sS -k --connect-timeout 6 --max-time ${MAX_TIME} --retry ${RETRIES} --retry-connrefused --retry-delay 5"

out=$(curl ${ARGS} ${URL} | head -1 | tr '[:upper:]' '[:lower:]')
STATUS=$PIPESTATUS

##@@ TEMP
echo "$(now) ;; ARGS=$ARGS ;; URL=$URL ;; STATUS=$STATUS ;; out=$out " >> /tmp/check-healthz-debug.log

if [[ $STATUS != 0 ]]; then
  echo "CRITICAL; error trying to retrieve ${URL}"
  exit 2
fi

if [[ "${out}" == "ok"* ]]; then
  echo "OK"
  exit 0
elif [[ "${out}" == "all ok"* ]]; then
  echo "OK"
  exit 0
elif [[ "${out}" == *"warning"* ]]; then
  echo "WARNING: ${out}"
  exit 1
fi

echo "CRITICAL; saw : ${out}"
exit 2
