#!/bin/bash

EXPECT="$1"
shift

CURL_PARAMS="$@ -L -sS -k --connect-timeout 6 --max-time 55 --retry 10 --retry-connrefused --retry-delay 5"

outfile="/tmp/x"
cmd="curl -o $outfile ${CURL_PARAMS}"
$cmd

fgrep -q "$EXPECT" $outfile && { echo "OK"; exit 0; }

echo "CRITICAL- NOT FOUND: $EXPECT"
if [[ "$VERBOSE" != "" ]]; then
  echo "CMD: $cmd"
  echo "GOT: $(cat $outfile)"
fi
exit 2
