
ports:
  - 80:8080
  - 443:8443
  - 8443:8443

# redirect home.p0 so homesec delayed triggers come back to us.
extra_docker: "--add-host home.point0.net:127.0.0.1"


# NOTE unusual arrangement: webdock is bind-mounting views into several of
# nagdock's docker volumes.  This is because the Nagios cgi's assume the
# Nagios monitoring process is running on the same "machine."
# r+w access is given to nagdock/var_nagios/rw so the web interface can
# submit commands (silence, retry, etc) to the command queue.

mount_ro:
  - etc_apache2: /etc/apache2
  - home: /home
  - var_www: /var/www
  - /rw/dv/nagdock/var_log_nagios: /var/log/nagios
  - /rw/dv/nagdock/var_nagios: /var/nagios

mount_logs:
  - home_ken_homesec_data: /home/ken/homesec/data
  - var_log_apache2: /var/log/apache2

mount_persistent:
  - /rw/dv/nagdock/var_nagios/rw: /var/nagios/rw
  - /var/procmon: /var/procmon

