
autostart: 5

# defer to iptables to preserve external source IP addresses
#ports:
#  - 80:8080
#  - 443:8443
#  - 8443:8443

test_ports: ['8080:8080', '8443:8443']

mount_ro:
  - etc_apache2_keys: /etc/apache2/keys
  - var_www: /var/www
  - /rw/dv/nagdock/var_nagios: /var/nagios

mount_rw:
  - var_bookmarks: /var/bookmarks
  - var_log_apache2: /var/log/apache2
  - /rw/dv/nagdock/var_nagios/rw: /var/nagios/rw

extra_docker:
  - "--add-host=host:192.168.2.1"

test_vols:
  - var_log_apache2:
    owner: user/apache
    group: group/apache
    perm: "02750"
    
  - var_www:
    owner: user/root
    group: group/apache
    perm: "02750"
    
  - var_www/html:
    owner: user/root
    group: group/apache
    perm: "02750"
    
  - var_www/.ssh:
    owner: user/root
    group: group/apache
    perm: "02750"
    
  - var_www/.ssh/id_rsa.out:
    contents: "command:cd %targetdir%; ssh-keygen -N '' -f ./id_rsa"
    
  - var_www/make_links.out:
    contents: "command:cd %targetdir%; ln -s /usr/lib/cgi-bin; ln -s /var/log/apache2 logs; ln -s /run/apache2 run; ln -s /usr/lib/apache2 modules"
    
  - etc_apache2_keys:
    owner: user/root
    group: group/apache
    perm: "02750"
    
  - etc_apache2_keys/server-test-cert.out:
    owner: user/apache
    group: group/apache
    contents: "command:cd %targetdir%; openssl req -x509 -newkey rsa:4096 -days 5 -keyout server.key -out server.crt -nodes -subj '/C=US/ST=Virginia/L=NoTown/O=test.net/CN=test-cert'; cat server.crt server.key > server.pem; cp server.pem server-chain.pem; chown %owner%.%group% server*; chmod go+r *; chmod go-r *.key; "
  # TODO(defer): This is Ken specific (config from private.d); need to think about how to generalize this...
  
  - etc_apache2_keys/server-test-cert2.out:
    owner: user/apache
    group: group/apache
    contents: "command:cd %targetdir%; openssl req -x509 -newkey rsa:4096 -days 5 -keyout server-k3n.key -out server-k3n.crt -nodes -subj '/C=US/ST=Virginia/L=NoTown/O=test.net/CN=test-cert'; cat server-k3n.crt server-k3n.key > server-k3n.pem; cp server-k3n.pem server-chain-k3n.pem; chown %owner%.%group% server*; chmod go+r *; chmod go-r *.key; "

  - etc_apache2_keys/server-test-cert3.out:
    owner: user/apache
    group: group/apache
    contents: "command:cd %targetdir%; openssl req -x509 -newkey rsa:4096 -days 5 -keyout nc.key -out nc.crt -nodes -subj '/C=US/ST=Virginia/L=NoTown/O=test.net/CN=test-cert'; cp nc.crt nc-chain.crt; chown %owner%.%group% nc*; chmod go+r *; chmod go-r *.key; "
