#!/bin/bash

if [[ -z "$TEST" ]]; then
    CONFIG="/etc/nagios/nagios.cfg"
else
    echo "** RUNNING IN TEST MODE **"
    CONFIG="/etc/nagios/nagios-test.cfg"
    /dummy_server.py &
fi

exec /usr/sbin/nagios ${CONFIG}
