#!/bin/bash

# ---- fix ownerships & perms (container was built with mapped uid's)

chown -R relay.relay /home/relay
chmod go+rX /home

# ---------- transfer to real service

if [[ "$1" == "" ]]; then
    exec su -s -c '/home/relay/button_relay --logfile /var/log/button_relay.log' relay
else
    "$@"
fi
