
autostart: 5

# Use nat rather than docker proxy to preserve incoming source IP addr.

# Can't use default syslog driver, as we would miss our own failures.
log: journald

mount_rw:
  - /rw/log: /var/log

test_mount_rw:
  - var_log: /var/log

test_ports: ['1514:1514']

test_vols:
  - var_log:
    owner: "user/syslog"
    group: "group/syslog"
    perms: "0755"
    
  - var_log/queue:
    owner: "user/syslog"
    group: "group/syslog"
    perms: "0644"
    contents: ""
