
autostart: 5

# Use nat rather than docker proxy to preserve incoming source IP addr.

# Can't use default syslog driver, as we would miss our own failures.
log: journald

mount_rw:
  - /rw/log: /var/log

test_ports: ['1514:1514']

