#!/usr/bin/python3

'''Wrapper around hc with substring target selection.

Same basic CLI as hc: {target} [{command}], but target can be a partial substring
match for any tp-link device.  If substring is sufficiently specific that only one
match is found, it is automatically selected, otherwise, user is asked to select
from a list of matches.
'''

import os, sys
import kcore.uncommon as UC


def select(sel):
    targets = UC.popener(['q', 'ltp']).split(' ')
    matches = []
    for i in targets:
        if sel in i: matches.append(i)
    if not matches: sys.exit(f'No matches found for {sel}: {targets}')
    if len(matches) == 1: return matches[0]
    print('\nMultiple matches:')
    for match, i in enumerate(matches): print(f'  {i}.  {match}')

    i = UC.getch('Selection: ') if len(matches) < 10 else input('Selection: ')
    return matches[int(i)]


def main(argv):
    target = select(argv[1])
    command = argv[2] if len(argv) > 2 else 'on'
    print(f'hc {target} {command}')
    os.execlp('hc', 'hc', target, command)  # does not return.


if __name__ == '__main__':
    main(sys.argv)
