

all:
	@echo nothing to be done for :all

comp:
	@echo nothing to be done for :comp

clean:
	rm -rf __pycache__

install:
	@echo nothing to be done for :install

test:
	@echo nothing to be done for :test

update:
	@echo nothing to be done for :update

uninstall:
	@echo nothing to be done for :uninstall
